baseURL = "http://zouhuigang.github.io/"
title = "蓝蓝的小火苗 (www.anooc.com) "
subtitle = " 技术博客 "
languageCode = "en-us"
# preservetaxonomynames = true
theme = "hugo-travelify-theme"
DisqusShortname = "nikimonikado"
GoogleAnalytics = "UA-68204765-1"
canonifyURLs = true
# rssURI = "feed/" #deprecated feature
tags=["docker","hugo","git"]
categories=["资源管理"] 
[params]
    # Tell me who you are
    author = "邹慧刚"
    site_description = "欢迎技术交流,一个爱好golang/kubernetes的php程序员!"
    copyright  = "Copyright"
    avatar = "css/images/avatar.png"
    logo = "css/images/logo.png"
    disable_mathjax = false # set to true to disable MathJax

    # Format dates with Go's time formatting
    date_format = "January 02, 2006"

    # Add custom assets with their paths relative to the static folder
    custom_css = []
    custom_js  = []

[[menu.main]]
    name  = "首页"
    url   = "/"
    weight = 10

[[menu.main]]
    name  = "我的网站"
    url   = "http://www.anooc.com/"
    weight = 40
    
[[menu.main]]
    name  = "联系我们"
    url   = "/contact/"
    weight = 20

[social]
    github          = "zouhuigang"
    #flickr          = "nikimonikado"
    #instagram       = "nikimonikado"
    #youtube         = "nikimonikado"
    #vimeo           = "nikimonikado"
    #tumblr          = "nikimonikado"
    #linkedin        = "nikimonikado"
    #pinterest       = "nikimonikado"
    #googleplus      = "nikimonikado"
    #facebook        = "nikimonikado"
    #twitter         = "nikimonikado"



[params.slider]
    enable = true
    num_features = 6 

[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
    archives = false 
    search = true
    mailchimp = true
    mailchimpform = "//balaramadurai.us15.list-manage.com/subscribe/post?u=7f4183fa2fe7abe3dc9f4efad&amp;id=49a3dd3745"
    author = true
    facebook_like = true

[taxonomies]
    tags = "tags"
    categories = "categories"
    author =  "author"


