apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-mysql-master
  labels:
    name: mysql-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-master
    spec:
      containers:
      - name: mysql-master
        image: registry.cn-hangzhou.aliyuncs.com/zhg_docker_ali_r/mysql:master-1.0.0
        imagePullPolicy: IfNotPresent
        args: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--max_allowed_packet=32M"]
        env:
          - name: TZ
            value: 'Asia/Shanghai'
          - name: LANG
            value: 'C.UTF-8'
          - name: MYSQL_ROOT_PASSWORD
            value: 'demo'
          - name: MYSQL_DATABASE
            value: 'demo'
          - name: MYSQL_REPLICATION_USER
            value: 'repl'
          - name: MYSQL_REPLICATION_PASSWORD
            value: 'slave'
        ports:
        - containerPort: 3306
